version: '3.8'

services:
  runpod-accounting:
    image: registry.runpod.net/yangminjong-runpodaccount-main-dockerfile:latest
    container_name: runpod-accounting-service
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 32G
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - HF_TOKEN=${HF_TOKEN}
      - PYTHONUNBUFFERED=1
    volumes:
      - model_cache:/workspace/model_cache
    healthcheck:
      test: ["CMD", "python", "-c", "import torch; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  model_cache:
    driver: local