# RunPod 서버리스 설정 파일

[serverless]
# GPU 타입 설정 (A100, A40, RTX 3090 등)
gpu_type = "AMPERE_24"

# 최소/최대 워커 수
min_workers = 0
max_workers = 3

# 콜드 스타트 관리
idle_timeout = 60  # 60초 동안 요청이 없으면 워커 종료
active_workers = 1  # 항상 활성화된 워커 수

# 메모리 설정
memory_gb = 24
vram_gb = 24

# 환경 변수
[serverless.env]
CUDA_VISIBLE_DEVICES = "0"
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:512"

# 볼륨 마운트 (선택사항 - 모델 캐싱용)
[serverless.volume]
mount_path = "/workspace/model_cache"
size_gb = 50

# 헬스체크 설정
[serverless.health_check]
enabled = true
path = "/health"
interval = 30

# 로깅 설정
[serverless.logging]
level = "INFO"
format = "json"